const guidanceEquipment = [
      "Laser Guide Kit",
      "High-speed Laser Guide Kit",
      "Laser Guide Kit T2",
      "Laser Guide Kit T3",
      "Laser Guide Kit T4",
      "Guide Beacon Gun",
      "Guide Beacon Gun M2",
      "High Output Beacon Gun",
      "Guide Beacon Gun M3",
      "Power Beacon Gun",
      "Guide Beacon Gun MA"
    ];

const callingForSupport = [
      "Howitzer (Artillery Squad)",
      "Cannon A (Artillery Squad)",
      "Large Howitzer (Artillery Squad)",
      "Cannon B (Artillery Squad)",
      "Cannon C (Artillery Squad)",
      "Enhanced Howitzer (Artillery Squad)",
      "Gigantic Howitzer (Artillery Squad)",
      "Cannon D (Artillery Squad)",

      "Artillery A (Attack Whale)",
      "105mm Cannon (Attack Whale)",
      "150mm Cannon (Attack Whale)",
      "Artillery B (Attack Whale)",
      "120mm Cannon A (Attack Whale)",
      "150mm Cannon B (Attack Whale)",
      "120mm Cannon B (Attack Whale)",
      "Artillery C (Attack Whale)",
      "Artillery D (Attack Whale)",
      "150mm Cannon C (Attack Whale)",
      "120mm Cannon C (Attack Whale)",

      "Bombing Plan A (Bomber Charon)",
      "Strafe Plan A (Bomber Charon)",
      "Bombing Plan B (Bomber Charon)",
      "Bombing Plan C (Bomber Charon)",
      "Strafe Plan B (Bomber Charon)",
      "Bombing Plan D (Bomber Charon)",
      "Wave Attack (Bomber Charon)",
      "Cluster Hit (Bomber Midnight)",
      "Bombing Plan E (Bomber Charon)",
      "Strafe Plan C (Bomber Charon)",
      "Bombing Plan F (Bomber Charon)",

      "AH Coastal Missiles",
      "AH High-Speed Missile Group",
      "NX Large Coastal Missiles",
      "N5 Coastal Missiles",
      "Lionic 20",
      "Tempest A1",
      "N6 Coastal Missiles",
      "Tempest A2",
      "Lionic 30",
      "Tempest S1A",

      "Satellite Blaster A",
      "Spritefall A",
      "Satellite Blaster B",
      "Spritefall B",
      "Satellite Blaster C",
      "Spritefall C",
      "Satellite Blaster D",
      "Satellite Blaster E",
      "Laguna Blaster",
      "Rule of God"
    ];

const supportEquipment = [
      "Life Vendor",
      "Life Vendor M2",
      "Life Spout Gun",
      "Life Spout Gun M2",
      "Life Vendor M3",
      "Life Vendor MH",
      "Life Spout Gun M3",
      "Life Vendor ZD",
      "Life Spout Gun ZD",
      "Plasma Charger",
      "Plasma Battery Gun",
      "Plasma Charger M2",
      "Plasma Streamer",
      "Plasma Charger M3",
      "Plasma Battery Gun M2",
      "Plasma Streamer DA",
      "Plasma Charger ZM",
      "Plasma Battery Gun ZM",
      "Power Assist Gun",
      "Power Post",
      "Power Post M2",
      "Power Assist Gun M2",
      "Offensive Territory",
      "Power Assist Gun MG",
      "Power Post ZM",
      "Guard Post",
      "Guard Assist Gun",
      "Guard Post M2",
      "Zone Protector",
      "Guard Assist Gun G",
      "Guard Post M3",
      "Zone Protector ZM"
    ];

const limpetGuns = [
      "Limpet Gun",
      "Limpet Splendor",
      "Limpet Sniper",
      "Limpet Gun D",
      "Limpet Splendor D",
      "Limpet Gun M2",
      "Limpet Sniper D",
      "Limpet Splendor M2",
      "Limpet Launcher",
      "Limpet Splendor A30",
      "Limpet Gun M3",
      "Splendor Shot",
      "Limpet Splendor M3",
      "Limpet Chain Gun",
      "Limpet Sniper A3",
      "Limpet Detector",
      "Limpet Shot",
      "Limpet Buster",
      "Limpet Splendor M9",
      "Limpet Sniper F3",
      "Limpet Chain Gun M2",
      "Limpet Detector ME",
      "Limpet Gun MA",
      "Limpet Sniper MA2",
      "Splendor Chain Gun",
      "Limpet Gun MT",
      "Splendor Shot AX",
      "Limpet Heavy Gun",
      "Limpet Splendor ZD",
      "Limpet Sniper ZD",
      "Limpet Chain Gun ZD"
    ];

const stationaryWeapons = [
      "C20 Bomb",
      "Roller Bomb",
      "Assault Beetle",
      "C24 Bomb",
      "Roller Bomb D",
      "C25 Special Bomb",
      "Patroller",
      "Assault Beetle DA",
      "C30 Bomb",
      "Roller Bomb D2",
      "Stag Beetle",
      "Speed Star",
      "C70 Bomb",
      "Roller Bomb DZ",
      "Patroller DA",
      "Y9 Impulse",
      "Y9 Anti-Aircraft Impulse",
      "Y10 Impulse",
      "Y10 Anti-Aircraft Impulse",
      "Y10 Wide Impulse",
      "Y11 Impulse",
      "Y11 Anti-Aircraft Impulse",
      "Y20 Impulse",
      "YDX Anti-Aircraft Impulse",
      "YDX Strike Impulse",
      "Y21 Impulse",
      "ZE-GUN",
      "ZER-GUN",
      "ZE Sniper",
      "ZE Launcher",
      "ZERA-GUN",
      "ZE-GUN10",
      "ZEX Launcher",
      "ZEXR-GUN"
    ];

const specialWeapons = [
      "Pure Decoy Launchers *DLC",
      "Electromagnetic Bunker",
      "Decoy [Red]",
      "Anti-Aircraft Bunker",
      "Heavy Bunker",
      "Decoy [Blue]",
      "Electromagnetic Bunker M2",
      "Personal Shelter",
      "Electromagnetic Prison",
      "Decoy [Yellow]",
      "Anti-Aircraft Bunker ME",
      "Electromagnetic Bunker GH",
      "Borderline",
      "Decoy [Silver]",
      "Electromagnetic Wall",
      "Absolute Bunker",
      "Caesar Wire",
      "Rapidfire Wire",
      "Skytrap Wire",
      "Wire Shot",
      "Skytrap Wire 12W",
      "Rapidfire Wire DA",
      "Caesar Wire ZD",
      "Skytrap Wire 16W"
    ];

const tanks = [
      "E551 Gigantus",
      "E551 Gigantus D",
      "E551 Gigantus D2",
			//Gigantus Bullet Girls Marking
			//Gigantus DCC-Zero Marking
			//Gigantus DCC-Gogo. Marking
			//Gigantus EDF2 IfPS Marking
			//Gigantus Natsuiro High School Marking
      "Epsilon Armored Railgun",
      "E651 Titan",
      "E551 Gigantus J",
      "Melt Buster",
      "Epsilon Armored Railgun D",
      "E551 Gigantus JS Custom",
      "E551 Gigantus J2",
      "Epsilon Armored Railgun ME",
      "E551 Gigantus J3",
      "E651 Titan M2",
      "Epsilon Armored Railgun ME2",
      "E551 Gigantus G",
      "E551 Gigantus GS Custom",
      "Epsilon Armored Railgun MD4",
      "E551 Gigantus RG1",
      "Epsilon Armored Blast Railgun",
      "E551 Gigantus RG2",
      "E551 Gigantus ZS Custom",
      "E651 Titan M3",
      "Epsilon Armored Blast Railgun E",
      "E551 Gigantus ZA"
    ];

const groundVehicles = [
      "Armored Vehicle Grape",
      "Caravan Armored Vehicle",
      "Naegling Self-Propelled Rocket",
      "SDL1",
      "Armored Vehicle Grape AP1",
      "Caravan Armored Vehicle CS",
      "SDL1 Bike",
      "Naegling Self-Propelled Rocket XM",
      "Armored Vehicle Grape M2",
      "Armored Vehicle Grape RA",
      "Caravan Armored Vehicle M2",
      "SDL1 Type R",
      "Naegling Self-Propelled Rocket D1",
      "Armored Vehicle Grape AP2",
      "Caravan Armored Vehicle Turbo",
      "SDL1 Type Z",
      "Naegling Self-Propelled Rocket M3",
      "Armored Vehicle Grape M9",
      "Caravan Armored Vehicle M3",
      "SDL1 Burst Turbo",
      "Caravan Armored Vehicle S Turbo",
      "Armored Vehicle Grape RZ",
      "Naegling Self-Propelled Rocket XEM"
    ];

const helicopters = [
      "EF24 Bazelart",
      "EF31 Nereid",
      "HU04 Brute",
      "EF24 Bazelart Vulture",
      "EF31 Nereid (Mk.2)",
      "HU04 Brute Hell Flame",
      "EF24 Bazelart Blaze",
      "EF31 Fire Nereid",
      "HU04 Brute D7",
      "EF24 Bazelart Vulture 2",
      "EF31 Nereid S",
      "EF24 Bazelart Vulture F",
      "HU04 Brute SA9",
      "EF31 Nereid Angel",
      "EF24 Bazelart Powered"
    ];

const powerSuits = [
      "BM03 Vegalta Gold *DLC",
      "BM03 Vegalta",
			"Depth Crawler I *4.1",
			"Depth Crawler Gold Coat *4.1 DLC",
      "BM03 Vegalta Fire Warrior",
			"Depth Crawler Flame *4.1",
      "BM03 Vegalta D",
			"Depth Crawler II *4.1",
			"Walking Fortress Balam *4.1",
      "BM03 Vegalta Heavy Cannon",
      "BM03 Vegalta A1",
      "BMX10 Proteus",
			"Depth Crawler Heavy Custom *4.1",
      "BM03 Vegalta Missile Gun",
			"Walking Fortress Balam Type B *4.1",
      "BM03 Vegalta A2",
      "BM03 Vegalta Fireghost",
			"Depth Crawler III *4.1",
      "BM03 Vegalta Buster Arms",
			"Depth Crawler S Range Custom *4.1",
      "BMX10 Proteus Burst",
      "BM03 Vegalta AW4",
			"Walking Fortress Balam Laser Fort *4.1",
      "BM03 Vegalta Revolver Custom",
			"Depth Crawler L Range Custom *4.1",
      "BM03 Vegalta Fireknight",
      "BM03 Vegalta Busterlord",
			"Depth Crawler IV *4.1",
      "BMX10 Proteus Gamma",
      "BM03 Vegalta Firelord",
      "BM03 Vegalta AX",
			"Depth Crawler IV Custom *4.1",
			"Walking Fortress Balam Type F *4.1"
    ];

const categories = [
  { id:'guidance',        title:'Guidance Equipment',   names: guidanceEquipment },
  { id:'calling-support', title:'Calling For Support',  names: callingForSupport },
  { id:'support-equip',   title:'Support Equipment',    names: supportEquipment },
  { id:'limpet-guns',     title:'Limpet Guns',          names: limpetGuns },
  { id:'stationary',      title:'Stationary Weapons',   names: stationaryWeapons },
  { id:'special-weapons', title:'Special Weapons',      names: specialWeapons },
  { id:'tanks',           title:'Tanks',                names: tanks },
  { id:'ground-vehicles', title:'Ground Vehicles',      names: groundVehicles },
  { id:'helicopters',     title:'Helicopters',          names: helicopters },
  { id:'power-suits',     title:'Power Suits',          names: powerSuits }
].map(c=>({...c,total:c.names.length}));

createEDFPage({title:'Air Raider', categories, storageKey:'airraiderSave'});