const ccStrikers = [
      "Vibro Hammer",
			"Vibro Hammer F3",
			"Force Blade",
			"Vibro Roller",
			"Vibro Hammer FA",
      "Force Blade D",
			"Vibro Haken",
			"Vulcan Hammer",
			"Dynamo Blade",
			"Vibro Roller D2",
      "Vibro Hammer FV",
			"Force Ax",
			"Quake Haken",
			"Vulcan Hammer D",
			"Vibro Roller D3",
      "Dynamo Blade M2",
			"Quake Haken ZD",
			"Vulcan Hammer ZD",
			"Force Blade MA",
			"Force Ax G2",
      "Finest Hammer",
			"Force Ax G3",
			"Vibro Roller D9",
			"Dyna Force Blade"
    ];

const ccPiercers = [
      "Blasthole Spear",
			"Flashing Spear",
			"Jackhammer",
			"Spine Driver",
			"Blasthole Spear M2",
      "Blast Twin Spears",
			"Flashing Spear M2",
			"Jackhammer M2",
			"Spine Driver M2",
			"Flashing Spear M3",
      "Blasthole Spear M3",
			"Blast Twin Spears M2",
			"Blasthole Spear M4",
			"Jackhammer M3",
			"Spine Driver M3",
      "Flashing Spear M4",
			"Blasthole Spear M5",
			"Jackhammer M4",
			"Blast Twin Spears M3",
			"Blasthole Spear M6",
      "Spine Driver M4",
			"Jackhammer MA",
			"Blasthole Spear MS",
			"Blast Twin Spears M4",
			"Flashing Spear M5",
      "Spine Driver MA"
    ];

const shields = [
      "Deflection Shield",
			"Ion Mirror Shield",
			"Tower Shield",
			"Deflection Shield 2",
			"Ion Mirror Shield 2E",
      "Deflection Shield 3",
			"Tower Shield 2E",
			"Deflection Shield 4",
			"Ion Mirror Shield 3E",
			"Reflector",
      "Deflection Shield 5",
			"Tower Shield 3E",
			"Deflection Shield 6",
			"Ion Mirror Shield 4E",
			"Deflection Shield 7",
      "Tower Shield 4E",
			"Ion Mirror Shield 5E",
			"Deflection Shield MA",
			"Powered Reflector",
			"Deflection Shield MGX",
      "Ion Mirror Shield MG",
			"Master Shield",
			"Great Shield"
    ];

const autoArtillery = [
      "FG7 Hand Gatling",
			"Gallion Lightweight Cannon",
			"Dexter Automatic Shotgun",
			"Flame Revolver",
			"FG8 Hand Gatling",
      "Gallion Rapid Fire Cannon",
			"Dexter Automatic Shotgun D1",
			"Flame Revolver D",
			"UT1 Hand Gatling",
			"Gallion Lightweight Cannon M2",
      "Disruptor",
			"FG9 Hand Gatling",
			"FGS Diffusion Gatling",
			"Dexter Automatic Shotgun D2",
			"Gallion Triple Burst Cannon",
      "Flame Revolver DC1",
			"UT2 Hand Gatling",
			"Gallion Lightweight Cannon M3",
			"Dexter Automatic Shotgun G",
			"FG10 Hand Gatling",
      "Gallion 3R Burst Cannon",
			"Flame Revolver DC2",
			"Power Disruptor",
			"FG20 Hand Gatling",
			"Gallion Rapid Fire Cannon M2",
      "Dexter Automatic Shotgun ZA",
			"UT3 Hand Gatling",
			"Gallion Armor-Pierce Cannon",
			"Maximum Disruptor",
			"Dexter Automatic Shotgun ZG",
      "FGZ Hand Gatling",
			"Hell Flame Revolver"
    ];

const artillery = [
    	"NC101 Hand Cannon",
			"30mm Gallic Heavy Cannon",
			"Powerdyne",
			"NCS1 Cannon Shot",
    	"30mm Gallic Heavy Cannon M2",
			"Javelin Catapult",
			"25mm Light Canister Cannon",
    	"NC102 Hand Cannon",
			"NC103 Hand Cannon",
    	"30mm Gallic Heavy Cannon M3",
			"Javelin Storm",
			"NC104 Hand Cannon",
    	"NCS2 Cannon Shot",
			"NC201 Hand Cannon",
    	"Twin Javelin Catapult",
			"30mm Light Canister Cannon",
			"NC202 Hand Cannon",
    	"35mm Gallic Heavy Cannon",
			"Javelin Storm ZD",
			"NCSS Cannon Shot",
			"NC290 Hand Cannon",
			"35mm Battle Cannon",
			"FH11 Light Mortar",
			"Ifrit",
			"YH1 Dispersal Mortar",
    	"FHD1 Heavy Mortar",
			"YH2 Dispersal Mortar",
    	"FHD2 Heavy Mortar",
			"FH13 Light Mortar",
    	"FHD3 Heavy Mortar",
			"FH21 Light Mortar",
    	"YH3 Dispersal Mortar",
			"FH22 Mortar",
    	"FHER Explosion Mortar",
			"YH7 Dispersal Mortar"
		];

const missileLaunchers = [
			"Phoenix 1",
			"Arm Hound",
			"Blood Storm",
    	"Leviathan",
			"Haytal Multiple Missiles",
    	"Arcane 6-Barrel Missiles",
			"FG01 High Altitude Impact Missiles",
			"Phoenix 2",
    	"G2 Arm Hound",
			"Haytal Multiple Missiles M2",
			"M2 Blood Storm",
			"Leviathan MA",
    	"FG02 High Altitude Impact Missiles",
    	"Phoenix 3",
			"Arcane 6-Barrel Missiles G2",
    	"Haytal Multiple Missiles MA",
			"G3 Arm Hound",
			"Wild Leviathan",
    	"Phoenix X",
			"Arcane 6-Barrel Missiles GA",
    	"FGX High Altitude Impact Missiles",
    	"Haytal Multiple Missiles WX",
			"Phoenix WX"
		];

const categories = [
  { id:'cc-strikers',         title:'CC Strikers',         names: ccStrikers },
  { id:'cc-piercers',         title:'CC Piercers',         names: ccPiercers },
  { id:'shields',             title:'Shields',             names: shields },
  { id:'automatic-artillery', title:'Automatic Artillery', names: autoArtillery },
  { id:'artillery',           title:'Artillery',           names: artillery },
  { id:'missile-launchers',   title:'Missile Launchers',   names: missileLaunchers }
].map(c=>({...c,total:c.names.length}));

createEDFPage({title:'Fencer', categories, storageKey:'fencerSave'});