const assaultRifles = [
			"AF14",
			"AF14-RA",
			"AF14-ST",
			"Fusion Blaster",
			"AF14-RAR",
			"AF14-B3",
			"AF15",
			"AF15-ST",
			"Fusion Blaster G1",
			"AF16",
			"AF-V",
			"AF16-RA",
			"AF17",
			"AF18",
			"AF18-RA",
			"AF18-X",
			"AF19-ST",
			"Fusion Blaster G2",
			"AF19",
			"AF19-RA",
			"AF19X-B3",
			"AF20",
			"AF20-ST",
			"AF20-RAR",
			"AF21-B4",
			"Fusion Blaster DA",
			"AF99",
			"AF99-ST",
			"Fusion Blaster ZD",
			"AF100"
		];

const shotguns = [
			"Buffalo G1",
			"Sting Shot *4.1",
			"Buffalo G2",
			"Governor 25",
			"Wideshot",
			"Wideshot VR",
			"Slug Shot *4.1",
			"Sparrow Shot",
			"Buffalo G3 Burst",
			"Buffalo G3",
			"Sparrow Shot M2",
			"Slug Shot BC *4.1",
			"Governor 50",
			"Wideshot A1",
			"Buffalo G4",
			"Wideshot A1-VR",
			"Buffalo G9",
			"Sparrow Shot M3",
			"Governor 100",
			"Buffalo GSS",
			"Slug Shot DA *4.1",
			"Sparrow Shot MX",
			"Slug Shot EA *4.1",
			"Buffalo Wide"
		];

const sniperRifles = [
			"MMF40",
			"MMF40-RA",
			"Stringer",
			"MMF41",
			"MMF41-B3",
			"Lysander",
			"MMF42",
			"Nova Buster",
			"MMF42-RA",
			"Zero Laser Rifle",
			"MMF43",
			"MMF43-B2",
			"Stringer J2",
			"MMF50",
			"Five Card XA",
			"Lysander 2",
			"MMF100",
			"Five Card XB",
			"Stringer J3",
			"Nova Buster DA",
			"MMF200",
			"Lysander F",
			"Nova Buster ZD",
			"Stringer J9",
			"Hercules",
			"Lysander Z"
		];

const rocketLaunchers = [
			"Stingray M1",
			"Stingray ST",
			"Volcano 3A",
			"Stingray ST2",
			"Volcano 3W-Burst",
			"Cascade 1",
			"A1 Plasma Bomber",
			"Goliath D1",
			"Stingray M2",
			"Stingray M3",
			"A2 Plasma Bomber",
			"Cascade 2",
			"Goliath D2",
			"Stingray M4",
			"Volcano B10",
			"Goliath Z",
			"Volcano 6W",
			"A3 Plasma Bomber",
			"Stingray M99",
			"Cascade Iota *4.1",
			"Stingray MF"
			//Genocide Gun
		];

const missileLaunchers = [
			"Air Tortoise 01",
			"ME1 Emerald",
			"MLRA",
			"Air Tortoise 02",
			"ME2 Emerald",
			"FORK-A15",
			"MLRA-2",
			"ME3 Emerald",
			"MLRA-30",
			"Prominence M1",
			"FORK-A20",
			"ME4 Emerald",
			"Air Tortoise ME",
			"MLRA-TW",
			"Prominence M2",
			"FORK-X20",
			"MEX5 Emerald",
			"Prominence MA"
		];

const grenades = [
			"MG11",
			"MG11J",
			"DNG1",
			"MG12",
			"MG13",
			"MG13J",
			"MG14",
			"MG14J",
			"DNG2",
			"MG20",
			"MG21J",
			"DNG3",
			"Bound Grenade",
			"DNG9",
			"UM1 Grenade Launcher",
			"UM1-J Grenade Launcher",
			"Volatile Napalm *DLC",
			"Stampede M1",
			"UM2 Grenade Launcher",
			"UM2-J Grenade Launcher",
			"UMRA Grenade Launcher",
			"UM3-J Grenade Launcher",
			"Splash Grenade",
			"Sticky Grenade Prototype",
			"UM4 Grenade Launcher",
			"BRUTE-J Triple Grenade Launcher",
			"Flame Geyser",
			"Splash Grenade α",
			"Volatile Napalm D",
			"BRUTE Triple Grenade Launcher",
			"Sticky Grenade",
			"Stampede M2",
			"CRUMBLE Twin Grenade Launcher",
			"Volcanic Napalm",
			"Sticky Grenade α",
			"UMAX Grenade Launcher",
			"Flame Geyser DA",
			"Stampede XM",
			"Volatile Napalm ZD",
			"UMAZ Grenade Launcher *4.1"
		];

const specialWeapons = [
			"Pure Decoy Launchers *DLC",
			"Acid Shot Prototype",
			"Acid Gun",
			"Acid Shot",
			"Wide Acid Gun",
			"Super Acid Gun",
			"Torch",
			"Flamethrower",
			"Flamethrower α",
			"Flame Cannon",
			"Magma Cannon",
			"Firecracker 1",
			"Firecracker 2",
			"Firecracker 3",
			"Firecracker 4",
			"Burst Firecracker",
			"P78 Bound Gun",
			"P79 Bound Gun",
			"P80 Bound Gun",
			"P89 Bound Gun",
			"PX50 Bound Shot",
			"Proto Reverser",
			"Reverser",
			"Reverse Gun",
			"High Cycle Reverser",
			"Reverser M2",
			"Reverse Shooter T1",
			"Reverser M3",
			"Reverse Bomber",
			"High Cycle Reverser D",
			"Reverse Shooter T2",
			"Reverser X",
			"Reverse Shooter X",
			"High Cycle Reverser ZD"
		];

const categories = [
  { id:'assault-rifles',   title:'Assault Rifles',   names: assaultRifles },
  { id:'shotguns',         title:'Shotguns',         names: shotguns },
  { id:'sniper-rifles',    title:'Sniper Rifles',    names: sniperRifles },
  { id:'rocket-launchers', title:'Rocket Launchers', names: rocketLaunchers },
  { id:'missile-launchers',title:'Missile Launchers',names: missileLaunchers },
  { id:'grenades',         title:'Grenades',         names: grenades },
  { id:'special-weapons',  title:'Special Weapons',  names: specialWeapons }
].map(c=>({...c,total:c.names.length}));

createEDFPage({title:'Ranger', categories, storageKey:'rangerSave'});