const shortRange = [
			"Rapier",
			"Laser Lance",
			"Spark Lancer *4.1",
			"Rapier Thrust",
  		"Laser Lance B",
			"M2 Rapier",
			"2-Way Lance",
  		"Plasma Ram",
			"Laser Lance R Custom",
			"M3 Rapier Thrust",
			"MX Laser Lance",
			"Plasma Whip",
			"Laser Lance C",
			"3-Way Lance",
  		"MX Rapier",
			"Burst Lance",
			"Rapier G Thrust",
			"Spark Lance *4.1",
  		"Laser Lance X",
			"Rapier G Thrust 2",
  		"Plasma Whip S",
			"Demonic Lance",
			"4-Way Lance",
			"Plasma Broom *Sweeper",
			"Master Rapier",
  		"Laser Lance Σ",
			"Spark Lance A *4.1",
			"Master Rapier Thrust",
  		"Sacred Lance",
			"Luonnotar",
			"Hreidmarr"
		];

const midRangeLasers = [
  		"LAZR-197",
			"Reflection Laser *DLC",
  		"LARG-V",
			"LAZR-198",
			"LAZR-199",
  		"LAZR-200",
			"Laser Chainsaw",
			"LAZR-201",
  		"Reflectron V Laser",
			"LAZR-202","LARG-W3",
  		"Reflectron Laser D",
			"Cyclone Laser",
  		"LAZR-299",
			"LAZR-300",
  		"Reflectron Multi-Laser",
			"ARC-LAZR",
  		"Reflectron Laser ZD",
			"SIG-LAZR"
		];

const midRangeElectroshock = [
			"Idunn-A",
			"Eclat 10",
			"Thunder Bow 10",
  		"Idunn-B",
			"Idunn-C Custom",
			"Eclat 20",
  		"Thunder Bow 15",
			"Thunder Bow 15S",
  		"Idunn-D Custom",
			"Thunder Bow 20",
  		"Grom X",
			"Grom SS",
			"Thunder Bow 20R",
  		"Idunn-E Custom",
			"Eclat 30",
  		"Idunn-E Custom 2",
			"Thunder Bow 30",
  		"Eclat LIM",
			"Idunn-FF",
			"Thunder Bow XD"
		];

const particleCannons = [
  		"Ixion",
			"Ixion 2-Way",
			"Ixion MX",
  		"Ixion Mark II",
			"Ixion 3-Way",
  		"Power Stringer",
			"Ixion Wide",
  		"Ixion 5-Way",
			"Ixion 4-Way",
  		"Dynastrike",
			"Ixion Mark III",
  		"Power Stringer D",
			"Ixion 6-Way",
  		"Dynastrike X",
			"Ixion 6-Way S",
  		"Dynastrike Z",
			"Dynastrike α",
  		"Ixion 9-Way",
			"Power Stringer S",
  		"Ixion Mark IV",
			"Ixion Mark X",
  		"Luxard"
		];

const sniperWeapons = [
  		"Proto Thunder Sniper",
			"LRSL-33",
			"LRSL-34",
  		"Thunder Sniper A",
			"LRSL-35",
			"LRSL-36",
  		"Monster",
			"Thunder Sniper B",
  		"Thunder Sniper 15",
			"Thunder Sniper C",
  		"Thunder Sniper R",
			"LRSL-37",
			"Raijin",
  		"LRSL-38",
			"Thunder Sniper D",
			"LRSL-S",
  		"Thunder Sniper 6",
			"Monster-S",
  		"Thunder Sniper 40",
			"Thunder Sniper MX",
  		"LRSL-AC",
			"SIG Sniper",
			"Gungnir"
		];

const rangedAttacks = [
  		"E1 Plasma Launcher",
			"Plasma Grenade A",
  		"Plasma Shot",
			"E2 Plasma Launcher",
  		"Plasma Grenade B",
			"E3 Plasma Launcher",
  		"Dual Plasma Launcher",
			"Rapid Grenade",
  		"D Plasma Launcher",
			"E4 Plasma Launcher",
  		"Blast Launcher",
			"Blast Grenade",
  		"3x Plasma Launcher",
			"D2 Plasma Launcher",
  		"Plasmafall",
			"M15 Plasma Launcher",
  		"Wide Grenade 20",
			"2x Plasma Launcher R",
  		"Plasma Grenade SP",
			"E5 Plasma Launcher",
  		"Plasma Grenade C",
			"2x Plasma Launcher S",
  		"EX Plasma Launcher",
			"EX3x Plasma Launcher",
  		"M30 Plasma Launcher",
			"Wide Grenade 40",
  		"RSR Plasma Launcher",
			"Plasma Grenade F",
  		"XSX Plasma Launcher",
			"Plasma Grenade Σ",
  		"Plasmafall Σ",
			"RZR Plasma Launcher"
		];

const homingWeapons = [
  		"Mirage Zero",
			"Geist",
			"Rapid Mirage",
  		"Mirage 5-Way",
			"Geist 2",
			"Mirage 5-Way B",
  		"Mirage Rumble",
			"Mirage 15",
			"Psiblade",
  		"Geist 3",
			"Mirage 15S",
			"Fenrir",
  		"Mirage 5-Way S",
			"Psiblade α",
			"Geist D",
  		"Ghost Chaser",
			"Mirage 15WR",
			"Fenrir 3-Way"
		];

const specialWeapons = [
  		"Pandora",
			"Gleipnir *DLC",
			"Heaven’s Gate",
  		"Thunder Cluster",
			"Pandora Anti-air Custom",
  		"Pandora β",
			"Psi Cluster",
			"Pandora α",
  		"psi Cluster α",
			"Heaven’s Gate 10",
  		"Thunder Cluster α",
			"Heaven’s Gate D10",
  		"Thunder Orb",
			"Final Days"
			//Armageddon Cluster
		];

const categories = [
  { id:'short-range',        title:'Short-Range',           names: shortRange },
  { id:'mid-range-lasers',   title:'Mid-Rg Lasers',         names: midRangeLasers },
  { id:'mid-range-electro',  title:'Mid-Rg Electroshock',   names: midRangeElectroshock },
  { id:'particle-cannons',   title:'Particle Cannons',      names: particleCannons },
  { id:'sniper-weapons',     title:'Sniper Weapons',        names: sniperWeapons },
  { id:'ranged-attacks',     title:'Ranged Attacks',        names: rangedAttacks },
  { id:'homing-weapons',     title:'Homing Weapons',        names: homingWeapons },
  { id:'special-weapons',    title:'Special Weapons',       names: specialWeapons }
].map(c=>({...c,total:c.names.length}));

createEDFPage({title:'Wing Diver', categories, storageKey:'wingdiverSave'});